Fix NullPointer exception in PDFALTOOutlineSaxHandler
kermitt2/grobid pull request #715
Opened 2021-02-16 14:32 UTC by lucbouge

I observed the following error. 

févr. 12, 2021 3:20:44 PM org.grobid.core.document.Document addTokenizedDocument
GRAVE: Cannot parse file: my_dir/grobid-0.6.1/grobid-home/tmp/ZW3PpM4E9g.lxml_outline.xml

févr. 12, 2021 3:20:44 PM org.grobid.core.document.Document addTokenizedDocument
GRAVE: Cannot parse file: my_dir/grobid-0.6.1/grobid-home/tmp/ZW3PpM4E9g.lxml_outline.xml

févr. 12, 2021 3:20:46 PM org.grobid.core.engines.ProcessEngine createTraining
INFOS: 2 files processed.

it originates in an illegal nullPointer access in file PDFALTOOutlineSaxHandler.java. 

In understand that the error is not  that "GRAVE". According to @kermitt2, it is simply one of the generated XML file resulting from the PDF parsing which is not XML valid (very frequent) - it has no impact because the outline file (containing the table of content outline if available embedded in the PDF) is not exploited by GROBID for the moment - it's to allow some possible improvements in the future. The error is more a reminder for the developers... the XML parser that classifies it as "GRAVE" but it would be rather INFO for us.

Unfortunately, a side effect might have been overlooked. If father is null, then father.addChild(currentNode) is called with a nullPointer exception.

This exception is caught by catch (Exception e) at line 372 in grobid-core/src/main/java/org/grobid/core/document/Document.java where the error message "Cannot parse" is misleading.

I think an additional else is just missing.

2021-02-18 22:25 UTC, lfoppiano requested changes
Could you provide the pdf file (or the outline xml file) that causes this error? 

I'd like to add an unit test

2021-02-18 22:25 UTC, lfoppiano commented on grobid-core/src/main/java/org/grobid/core/sax/PDFALTOOutlineSaxHandler.java
> +                // Correction proposed by Luc Bougé @lucbouge
You don't need all these comments, your name will be registered anyway in the git history

2021-02-18 22:25 UTC, lfoppiano commented on grobid-core/src/main/java/org/grobid/core/sax/PDFALTOOutlineSaxHandler.java
>  				if (father == null)
Also this old code can be removed

2021-02-19 10:08 UTC, lucbouge commented
Thanks. I proceed today. Luc.

> Le 18 févr. 2021 à 23:25, Luca Foppiano <notifications@github.com> a écrit :
> 
> 
> @lfoppiano requested changes on this pull request.
>

2021-02-19 18:42 UTC, lucbouge commented
Here is a test file 
[test.pdf](https://github.com/kermitt2/grobid/files/6012135/test.pdf)

Here is the outcome with the original installation grobid-0.6.1. I singled out the trace of the bug. 

I also include below the trace with the pull request. 

Regards,

Luc.

### With the original installation

```
$ java -Xmx4G -jar grobid-core/build/libs/grobid-core-0.6.1-onejar.jar -gH grobid-home -dIn Input -dOut Output -exe createTraining

févr. 19, 2021 7:33:22 PM org.grobid.core.main.GrobidHomeFinder getGrobidHomePathOrLoadFromClasspath
AVERTISSEMENT: No Grobid property was provided. Attempting to find Grobid home in the current directory...
févr. 19, 2021 7:33:22 PM org.grobid.core.main.GrobidHomeFinder findGrobidHomeOrFail
AVERTISSEMENT: ***************************************************************
févr. 19, 2021 7:33:22 PM org.grobid.core.main.GrobidHomeFinder findGrobidHomeOrFail
AVERTISSEMENT: *** USING GROBID HOME: /Users/bouge/Repositories/no_save/tmp/grobid-0.6.1/grobid-home
févr. 19, 2021 7:33:22 PM org.grobid.core.main.GrobidHomeFinder findGrobidHomeOrFail
AVERTISSEMENT: ***************************************************************
févr. 19, 2021 7:33:22 PM org.grobid.core.main.GrobidHomeFinder getGrobidHomePathOrLoadFromClasspath
AVERTISSEMENT: No Grobid property was provided. Attempting to find Grobid home in the current directory...
févr. 19, 2021 7:33:22 PM org.grobid.core.main.GrobidHomeFinder findGrobidHomeOrFail
AVERTISSEMENT: ***************************************************************
févr. 19, 2021 7:33:22 PM org.grobid.core.main.GrobidHomeFinder findGrobidHomeOrFail
AVERTISSEMENT: *** USING GROBID HOME: /Users/bouge/Repositories/no_save/tmp/grobid-0.6.1/grobid-home
févr. 19, 2021 7:33:22 PM org.grobid.core.main.GrobidHomeFinder findGrobidHomeOrFail
AVERTISSEMENT: ***************************************************************
févr. 19, 2021 7:33:22 PM org.grobid.core.main.GrobidHomeFinder findGrobidPropertiesOrFail
AVERTISSEMENT: Grobid property file location was not explicitly set via 'org.grobid.property' system variable, defaulting to: /Users/bouge/Repositories/no_save/tmp/grobid-0.6.1/grobid-home/config/grobid.properties
févr. 19, 2021 7:33:22 PM org.grobid.core.utilities.GrobidProperties getEnvironmentVariableOverrides
INFOS: environment variables overrides: {}
févr. 19, 2021 7:33:22 PM org.grobid.core.main.LibraryLoader load
INFOS: Loading external native sequence labelling library
févr. 19, 2021 7:33:22 PM org.grobid.core.main.LibraryLoader load
INFOS: Loading Wapiti native library...
févr. 19, 2021 7:33:22 PM org.grobid.core.main.LibraryLoader load
INFOS: Native library for sequence labelling loaded
févr. 19, 2021 7:33:22 PM org.grobid.core.lexicon.Lexicon initDictionary
INFOS: Initiating dictionary
févr. 19, 2021 7:33:22 PM org.grobid.core.lexicon.Lexicon initDictionary
INFOS: End of Initialization of dictionary
févr. 19, 2021 7:33:22 PM org.grobid.core.lexicon.Lexicon initNames
INFOS: Initiating names
févr. 19, 2021 7:33:22 PM org.grobid.core.lexicon.Lexicon initNames
INFOS: End of initialization of names
févr. 19, 2021 7:33:22 PM org.grobid.core.lexicon.Lexicon initCountryCodes
INFOS: Initiating country codes
févr. 19, 2021 7:33:22 PM org.grobid.core.lexicon.Lexicon initCountryCodes
INFOS: End of initialization of country codes
test.pdf
1 files to be processed.
Input/test.pdf
févr. 19, 2021 7:33:22 PM org.grobid.core.jni.WapitiModel init
INFOS: Loading model: /Users/bouge/Repositories/no_save/tmp/grobid-0.6.1/grobid-home/models/fulltext/model.wapiti (size: 21913642)
[Wapiti] Loading model: "/Users/bouge/Repositories/no_save/tmp/grobid-0.6.1/grobid-home/models/fulltext/model.wapiti"
Model path: /Users/bouge/Repositories/no_save/tmp/grobid-0.6.1/grobid-home/models/fulltext/model.wapiti

############## Here is the bug!
Warning, father not yet encountered! id is 1
févr. 19, 2021 7:33:25 PM org.grobid.core.document.Document addTokenizedDocument
GRAVE: Cannot parse file: /Users/bouge/Repositories/no_save/tmp/grobid-0.6.1/grobid-home/tmp/9bHVcUR99j.lxml_outline.xml
##########################

févr. 19, 2021 7:33:25 PM org.grobid.core.jni.WapitiModel init
INFOS: Loading model: /Users/bouge/Repositories/no_save/tmp/grobid-0.6.1/grobid-home/models/segmentation/model.wapiti (size: 27668093)
[Wapiti] Loading model: "/Users/bouge/Repositories/no_save/tmp/grobid-0.6.1/grobid-home/models/segmentation/model.wapiti"
Model path: /Users/bouge/Repositories/no_save/tmp/grobid-0.6.1/grobid-home/models/segmentation/model.wapiti
Warning, father not yet encountered! id is 1
févr. 19, 2021 7:33:29 PM org.grobid.core.document.Document addTokenizedDocument
GRAVE: Cannot parse file: /Users/bouge/Repositories/no_save/tmp/grobid-0.6.1/grobid-home/tmp/9bHVcUR99j.lxml_outline.xml
févr. 19, 2021 7:33:29 PM org.grobid.core.jni.WapitiModel init
INFOS: Loading model: /Users/bouge/Repositories/no_save/tmp/grobid-0.6.1/grobid-home/models/reference-segmenter/model.wapiti (size: 4921245)
[Wapiti] Loading model: "/Users/bouge/Repositories/no_save/tmp/grobid-0.6.1/grobid-home/models/reference-segmenter/model.wapiti"
Model path: /Users/bouge/Repositories/no_save/tmp/grobid-0.6.1/grobid-home/models/reference-segmenter/model.wapiti
févr. 19, 2021 7:33:30 PM org.grobid.core.jni.WapitiModel init
INFOS: Loading model: /Users/bouge/Repositories/no_save/tmp/grobid-0.6.1/grobid-home/models/citation/model.wapiti (size: 16412787)
[Wapiti] Loading model: "/Users/bouge/Repositories/no_save/tmp/grobid-0.6.1/grobid-home/models/citation/model.wapiti"
Model path: /Users/bouge/Repositories/no_save/tmp/grobid-0.6.1/grobid-home/models/citation/model.wapiti
févr. 19, 2021 7:33:32 PM org.grobid.core.jni.WapitiModel init
INFOS: Loading model: /Users/bouge/Repositories/no_save/tmp/grobid-0.6.1/grobid-home/models/figure/model.wapiti (size: 422671)
[Wapiti] Loading model: "/Users/bouge/Repositories/no_save/tmp/grobid-0.6.1/grobid-home/models/figure/model.wapiti"
Model path: /Users/bouge/Repositories/no_save/tmp/grobid-0.6.1/grobid-home/models/figure/model.wapiti
févr. 19, 2021 7:33:32 PM org.grobid.core.jni.WapitiModel init
INFOS: Loading model: /Users/bouge/Repositories/no_save/tmp/grobid-0.6.1/grobid-home/models/header/model.wapiti (size: 15734670)
[Wapiti] Loading model: "/Users/bouge/Repositories/no_save/tmp/grobid-0.6.1/grobid-home/models/header/model.wapiti"
Model path: /Users/bouge/Repositories/no_save/tmp/grobid-0.6.1/grobid-home/models/header/model.wapiti
févr. 19, 2021 7:33:57 PM org.grobid.core.jni.WapitiModel init
INFOS: Loading model: /Users/bouge/Repositories/no_save/tmp/grobid-0.6.1/grobid-home/models/affiliation-address/model.wapiti (size: 2699936)
[Wapiti] Loading model: "/Users/bouge/Repositories/no_save/tmp/grobid-0.6.1/grobid-home/models/affiliation-address/model.wapiti"
Model path: /Users/bouge/Repositories/no_save/tmp/grobid-0.6.1/grobid-home/models/affiliation-address/model.wapiti
févr. 19, 2021 7:34:03 PM org.grobid.core.engines.ProcessEngine createTraining
INFOS: 1 files processed.
```

### With the pull request

```
$ java -Xmx4G -jar grobid-core/build/libs/grobid-core-0.6.1-onejar.jar -gH grobid-home -dIn Input -dOut Output -exe createTraining

févr. 19, 2021 7:38:56 PM org.grobid.core.main.GrobidHomeFinder getGrobidHomePathOrLoadFromClasspath
AVERTISSEMENT: No Grobid property was provided. Attempting to find Grobid home in the current directory...
févr. 19, 2021 7:38:56 PM org.grobid.core.main.GrobidHomeFinder findGrobidHomeOrFail
AVERTISSEMENT: ***************************************************************
févr. 19, 2021 7:38:56 PM org.grobid.core.main.GrobidHomeFinder findGrobidHomeOrFail
AVERTISSEMENT: *** USING GROBID HOME: /Users/bouge/Repositories/no_save/tmp/grobid-0.6.1/grobid-home
févr. 19, 2021 7:38:56 PM org.grobid.core.main.GrobidHomeFinder findGrobidHomeOrFail
AVERTISSEMENT: ***************************************************************
févr. 19, 2021 7:38:56 PM org.grobid.core.main.GrobidHomeFinder getGrobidHomePathOrLoadFromClasspath
AV [...]

2021-02-21 19:04 UTC, kermitt2 commented
I think the parsing has to fail at this point, explicitly, not to continue, because the overall outline is not valid and we should not use it. So raising an exception is needed... and for me there is no bug, it's a necessity to have a parsing failure, though I agree that the "GRAVE" or "SEVERE" is misleading (there is no impact on GROBID output because outline is not used currently).  

We could have this:

```
if (father == null)
	throw new GrobidResourceException(Father not yet encountered! id is " + currentParentId, e);
currentNode.setFather(father);
```

and then catch this particular exception to log it as `warn` in the calling class `DocumentSource.java`.

2021-02-22 09:15 UTC, lucbouge commented
Yes, I agree. An important point is to raise a `GrobidResourceException` right there. Let me update my pull request agreeingly, labeling the error with something less stressing that SEVERE. 

NB: I spotted another occurrences of the same phenomenon. In that case, the exception is caught at line 356 in `Document.java`. It seems to be of the same nature. Let me have a closer look at it. 


> I think the parsing has to fail at this point, explicitly, not to continue, because the overall outline is not valid and we should not use it. So raising an exception is needed... and for me there is no bug, it's a necessity to have a parsing failure, though I agree that the "GRAVE" or "SEVERE" is misleading (there is no impact on GROBID output because outline is not used currently).
> 
> We could have this:
> 
> ```
> if (father == null)
> 	throw new GrobidResourceException(Father not yet encountered! id is " + currentParentId, e);
> currentNode.setFather(father);
> ```
> 
> and then catch this particular exception to log it as `warn` in the calling class `DocumentSource.java`.

2021-02-22 09:44 UTC, lucbouge commented
I made the correction. Is it clear that it only aborts processing the faulty file, without interrupting the correct ones?

2021-03-02 03:24 UTC, lfoppiano commented
@lucbouge the test file that you shared, is it public? can be committed as a test case?

2021-03-02 05:50 UTC, lfoppiano commented
I've integrated only the outline in the test cases. 
I've found few more bugs in that class, that I should have fixed hopefully without breaking anything else 😅

2021-03-02 05:59 UTC, lfoppiano commented
@lucbouge maybe we can update this PR if you position yourself in your repository and pull from the branch `lucbouge-patch-1`... I'm not sure it will work... something like... 

```bash 
git pull https://github.com/kermitt2/grobid.git lucbouge-patch-1
```

2021-03-05 02:26 UTC, lfoppiano approved these changes

2021-03-09 22:27 UTC, lfoppiano commented
OK. I close this in favour of #729, which contains my updates.

2021-03-09 22:27 UTC, closed without merging